# Generated by Django 2.2.5 on 2019-11-21 16:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20191121_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sce_geo', models.CharField(max_length=50)),
                ('sce_sem', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('origine', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=3)),
                ('nom', models.CharField(max_length=50)),
                ('superficie', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
