# Generated by Django 2.2.5 on 2019-11-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='picture',
            field=models.ImageField(default='C:\\Users\\Arthur Tankwa\\Documents\\Certificats\\Capture.png', upload_to=''),
        ),
    ]
