# Generated by Django 2.2.5 on 2019-11-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_auto_20191125_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidence',
            old_name='location',
            new_name='geom',
        ),
    ]
