# Generated by Django 2.2.5 on 2019-12-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0008_auto_20191125_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borne',
            name='picture',
            field=models.ImageField(default='C:\\defaut.jpg', upload_to=''),
        ),
    ]
