# Generated by Django 2.2.5 on 2019-12-11 13:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0010_auto_20191209_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bornes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('picture', models.ImageField(default='C:\\Users\\Arthur Tankwa\\Documents\\tutos\\programmation\\python\\Django\\Geodjango\\agricom\\reporter\\defaut.jpg', upload_to='')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Borne',
        ),
    ]
