# Generated by Django 2.2.5 on 2019-12-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20191211_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bornes',
            new_name='Borne',
        ),
    ]
