# Generated by Django 2.2.5 on 2020-01-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0012_auto_20191211_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borne',
        ),
    ]
