# Generated by Django 2.2.5 on 2020-01-09 18:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0013_delete_borne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('east', models.FloatField()),
                ('nord', models.FloatField()),
                ('picture', models.ImageField(default='C:\\Users\\Arthur Tankwa\\Documents\\tutos\\programmation\\python\\Django\\Geodjango\\agricom\\defaut.jpg', upload_to='')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
