# Generated by Django 2.2.5 on 2020-01-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0014_borne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borne',
        ),
    ]
