# Generated by Django 2.2.5 on 2020-01-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0016_borne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borne',
            name='east',
        ),
        migrations.RemoveField(
            model_name='borne',
            name='nord',
        ),
    ]
