# Generated by Django 2.2.5 on 2020-01-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0017_auto_20200109_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borne',
        ),
    ]
