# Generated by Django 2.2.5 on 2020-03-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0019_borne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borne',
            name='picture',
            field=models.ImageField(default='C:\\Users\\Arthur Tankwa\\github\\Portail-RGNC\\agricom\\reporter\\data\\default.jpg', upload_to=''),
        ),
    ]
